# Generated by Django 6.0.4 on 2026-04-18 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la résolution')),
                ('question', models.TextField(verbose_name='Question (binaire)')),
                ('context', models.TextField(blank=True, verbose_name='Contexte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
        ),
    ]
