# Generated by Django 6.0.4 on 2026-04-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='status',
            field=models.CharField(choices=[('draft', 'En cours de création'), ('evaluation', "En cours d'évaluation"), ('voting', 'En cours de vote'), ('resolved', 'Résolue')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
