# Generated by Django 6.0.4 on 2026-04-29 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapage', '0005_userresolutioncomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('for', 'Pour'), ('against', 'Contre')], max_length=10, verbose_name='Choix')),
                ('judgment', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('average', 'Passable'), ('bad', 'Mauvais'), ('reject', 'À rejeter')], max_length=20, verbose_name='Jugement')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du vote')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapage.resolution', verbose_name='Résolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'unique_together': {('user', 'resolution')},
            },
        ),
    ]
