# Generated by Django 6.0.4 on 2026-04-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapage', '0006_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='judgment',
        ),
        migrations.AddField(
            model_name='vote',
            name='judgment_against',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('average', 'Passable'), ('bad', 'Mauvais'), ('reject', 'À rejeter')], default='average', max_length=20, verbose_name='Jugement contre'),
        ),
        migrations.AddField(
            model_name='vote',
            name='judgment_for',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('average', 'Passable'), ('bad', 'Mauvais'), ('reject', 'À rejeter')], default='average', max_length=20, verbose_name='Jugement pour'),
        ),
    ]
